if(EXISTS "/Users/stevemitchell/Documents/GitHub/LiveCalc/livecalc-engine/build-cli/tests-b12d07c_tests.cmake")
  include("/Users/stevemitchell/Documents/GitHub/LiveCalc/livecalc-engine/build-cli/tests-b12d07c_tests.cmake")
else()
  add_test(tests_NOT_BUILT-b12d07c tests_NOT_BUILT-b12d07c)
endif()
